version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_rental
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306" # MySQL default port
    volumes:
      - ../database/mysql/sql:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7
    container_name: mongodb_database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: movieRental
    ports:
      - "27017:27017" # MongoDB default port
    volumes:
      - ../database/mongodb:/docker-entrypoint-initdb.d:ro
      - ../database/mongodb/init_replica.sh:/init_replica.sh:ro
      - mongodb_data:/data/db
    entrypoint: ["bash", "/init_replica.sh"]
    command: ["docker-entrypoint.sh", "mongod", "--replSet", "rs0", "--keyFile", "/data/replica.key", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:27017\"}]}).ok || rs.status().ok" | mongosh -u root -p root --quiet) -eq 1
      interval: 10s
      start_period: 30s

  api:
    build: ..
    container_name: movie_rental_api
    working_dir: /app
    command: python -m src.app
    environment:
      FLASK_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: movie_rental
      MONGO_URI: "mongodb://root:root@mongodb:27017/?authSource=admin"
      MONGO_DB_NAME: movieRental
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ..:/app
    ports:
      - "5004:5004"
    depends_on:
      - mysql
      - mongodb

volumes:
  mysql_data:
  mongodb_data: