version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_rental
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306" # MySQL default port
    volumes:
      - ../database/mysql/sql:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7
    container_name: mongodb_database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: movieRental
    ports:
      - "27017:27017" # MongoDB default port
    volumes:
      - ../database/mongodb:/docker-entrypoint-initdb.d:ro
      - mongodb_data:/data/db

  api:
    build: ..
    container_name: movie_rental_api
    working_dir: /app
    command: python -m src.app
    environment:
      # Flask configuration
      FLASK_ENV: development

      # MySQL configuration
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: movie_rental

      # MongoDB configuration
      MONGO_URI: mongodb://root:root@mongodb:27017
      MONGO_DB_NAME: movieRental
    volumes:
      - ..:/app
    ports:
      - "5004:5004" # API port
    depends_on:
      - mysql
      - mongodb

volumes:
  mysql_data:
  mongodb_data: